/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteRouteImport } from './routes/signup/route'
import { Route as SellerRouteRouteImport } from './routes/seller/route'
import { Route as ProfileRouteRouteImport } from './routes/profile/route'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as ChatRouteRouteImport } from './routes/chat/route'
import { Route as CatalogRouteRouteImport } from './routes/catalog/route'
import { Route as CartRouteRouteImport } from './routes/cart/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FarmsIndexRouteImport } from './routes/farms/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as ChatIdRouteImport } from './routes/chat/$id'
import { Route as SellerProfileRouteRouteImport } from './routes/seller/profile/route'
import { Route as ProductsIdRouteRouteImport } from './routes/products/$id/route'
import { Route as FarmsIdRouteRouteImport } from './routes/farms/$id/route'
import { Route as FarmersIdRouteRouteImport } from './routes/farmers/$id/route'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as SellerProductsIndexRouteImport } from './routes/seller/products/index'
import { Route as SellerFarmIndexRouteImport } from './routes/seller/farm/index'
import { Route as SellerProductsNewRouteRouteImport } from './routes/seller/products/new/route'
import { Route as SellerProductsIdEditRouteRouteImport } from './routes/seller/products/$id/edit/route'

const SignupRouteRoute = SignupRouteRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRouteRoute = SellerRouteRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRouteRoute = ProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRouteRoute = ChatRouteRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRouteRoute = CatalogRouteRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRouteRoute = CartRouteRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmsIndexRoute = FarmsIndexRouteImport.update({
  id: '/farms/',
  path: '/farms/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRouteRoute,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ChatRouteRoute,
} as any)
const SellerProfileRouteRoute = SellerProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SellerRouteRoute,
} as any)
const ProductsIdRouteRoute = ProductsIdRouteRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmsIdRouteRoute = FarmsIdRouteRouteImport.update({
  id: '/farms/$id',
  path: '/farms/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmersIdRouteRoute = FarmersIdRouteRouteImport.update({
  id: '/farmers/$id',
  path: '/farmers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const SellerProductsIndexRoute = SellerProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => SellerRouteRoute,
} as any)
const SellerFarmIndexRoute = SellerFarmIndexRouteImport.update({
  id: '/farm/',
  path: '/farm/',
  getParentRoute: () => SellerRouteRoute,
} as any)
const SellerProductsNewRouteRoute = SellerProductsNewRouteRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => SellerRouteRoute,
} as any)
const SellerProductsIdEditRouteRoute =
  SellerProductsIdEditRouteRouteImport.update({
    id: '/products/$id/edit',
    path: '/products/$id/edit',
    getParentRoute: () => SellerRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRouteRoute
  '/catalog': typeof CatalogRouteRoute
  '/chat': typeof ChatRouteRouteWithChildren
  '/login': typeof LoginRouteRoute
  '/profile': typeof ProfileRouteRoute
  '/seller': typeof SellerRouteRouteWithChildren
  '/signup': typeof SignupRouteRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRoute
  '/farmers/$id': typeof FarmersIdRouteRoute
  '/farms/$id': typeof FarmsIdRouteRoute
  '/products/$id': typeof ProductsIdRouteRoute
  '/seller/profile': typeof SellerProfileRouteRoute
  '/chat/$id': typeof ChatIdRoute
  '/chat/': typeof ChatIndexRoute
  '/farms/': typeof FarmsIndexRoute
  '/seller/products/new': typeof SellerProductsNewRouteRoute
  '/seller/farm/': typeof SellerFarmIndexRoute
  '/seller/products/': typeof SellerProductsIndexRoute
  '/seller/products/$id/edit': typeof SellerProductsIdEditRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRouteRoute
  '/catalog': typeof CatalogRouteRoute
  '/login': typeof LoginRouteRoute
  '/profile': typeof ProfileRouteRoute
  '/seller': typeof SellerRouteRouteWithChildren
  '/signup': typeof SignupRouteRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRoute
  '/farmers/$id': typeof FarmersIdRouteRoute
  '/farms/$id': typeof FarmsIdRouteRoute
  '/products/$id': typeof ProductsIdRouteRoute
  '/seller/profile': typeof SellerProfileRouteRoute
  '/chat/$id': typeof ChatIdRoute
  '/chat': typeof ChatIndexRoute
  '/farms': typeof FarmsIndexRoute
  '/seller/products/new': typeof SellerProductsNewRouteRoute
  '/seller/farm': typeof SellerFarmIndexRoute
  '/seller/products': typeof SellerProductsIndexRoute
  '/seller/products/$id/edit': typeof SellerProductsIdEditRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/cart': typeof CartRouteRoute
  '/catalog': typeof CatalogRouteRoute
  '/chat': typeof ChatRouteRouteWithChildren
  '/login': typeof LoginRouteRoute
  '/profile': typeof ProfileRouteRoute
  '/seller': typeof SellerRouteRouteWithChildren
  '/signup': typeof SignupRouteRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRoute
  '/farmers/$id': typeof FarmersIdRouteRoute
  '/farms/$id': typeof FarmsIdRouteRoute
  '/products/$id': typeof ProductsIdRouteRoute
  '/seller/profile': typeof SellerProfileRouteRoute
  '/chat/$id': typeof ChatIdRoute
  '/chat/': typeof ChatIndexRoute
  '/farms/': typeof FarmsIndexRoute
  '/seller/products/new': typeof SellerProductsNewRouteRoute
  '/seller/farm/': typeof SellerFarmIndexRoute
  '/seller/products/': typeof SellerProductsIndexRoute
  '/seller/products/$id/edit': typeof SellerProductsIdEditRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/catalog'
    | '/chat'
    | '/login'
    | '/profile'
    | '/seller'
    | '/signup'
    | '/dashboard'
    | '/farmers/$id'
    | '/farms/$id'
    | '/products/$id'
    | '/seller/profile'
    | '/chat/$id'
    | '/chat/'
    | '/farms/'
    | '/seller/products/new'
    | '/seller/farm/'
    | '/seller/products/'
    | '/seller/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/catalog'
    | '/login'
    | '/profile'
    | '/seller'
    | '/signup'
    | '/dashboard'
    | '/farmers/$id'
    | '/farms/$id'
    | '/products/$id'
    | '/seller/profile'
    | '/chat/$id'
    | '/chat'
    | '/farms'
    | '/seller/products/new'
    | '/seller/farm'
    | '/seller/products'
    | '/seller/products/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cart'
    | '/catalog'
    | '/chat'
    | '/login'
    | '/profile'
    | '/seller'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/farmers/$id'
    | '/farms/$id'
    | '/products/$id'
    | '/seller/profile'
    | '/chat/$id'
    | '/chat/'
    | '/farms/'
    | '/seller/products/new'
    | '/seller/farm/'
    | '/seller/products/'
    | '/seller/products/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CartRouteRoute: typeof CartRouteRoute
  CatalogRouteRoute: typeof CatalogRouteRoute
  ChatRouteRoute: typeof ChatRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRoute
  ProfileRouteRoute: typeof ProfileRouteRoute
  SellerRouteRoute: typeof SellerRouteRouteWithChildren
  SignupRouteRoute: typeof SignupRouteRoute
  FarmersIdRouteRoute: typeof FarmersIdRouteRoute
  FarmsIdRouteRoute: typeof FarmsIdRouteRoute
  ProductsIdRouteRoute: typeof ProductsIdRouteRoute
  FarmsIndexRoute: typeof FarmsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farms/': {
      id: '/farms/'
      path: '/farms'
      fullPath: '/farms/'
      preLoaderRoute: typeof FarmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRouteRoute
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof ChatRouteRoute
    }
    '/seller/profile': {
      id: '/seller/profile'
      path: '/profile'
      fullPath: '/seller/profile'
      preLoaderRoute: typeof SellerProfileRouteRouteImport
      parentRoute: typeof SellerRouteRoute
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farms/$id': {
      id: '/farms/$id'
      path: '/farms/$id'
      fullPath: '/farms/$id'
      preLoaderRoute: typeof FarmsIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmers/$id': {
      id: '/farmers/$id'
      path: '/farmers/$id'
      fullPath: '/farmers/$id'
      preLoaderRoute: typeof FarmersIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/seller/products/': {
      id: '/seller/products/'
      path: '/products'
      fullPath: '/seller/products/'
      preLoaderRoute: typeof SellerProductsIndexRouteImport
      parentRoute: typeof SellerRouteRoute
    }
    '/seller/farm/': {
      id: '/seller/farm/'
      path: '/farm'
      fullPath: '/seller/farm/'
      preLoaderRoute: typeof SellerFarmIndexRouteImport
      parentRoute: typeof SellerRouteRoute
    }
    '/seller/products/new': {
      id: '/seller/products/new'
      path: '/products/new'
      fullPath: '/seller/products/new'
      preLoaderRoute: typeof SellerProductsNewRouteRouteImport
      parentRoute: typeof SellerRouteRoute
    }
    '/seller/products/$id/edit': {
      id: '/seller/products/$id/edit'
      path: '/products/$id/edit'
      fullPath: '/seller/products/$id/edit'
      preLoaderRoute: typeof SellerProductsIdEditRouteRouteImport
      parentRoute: typeof SellerRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRouteRoute: AuthenticatedDashboardRouteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ChatRouteRouteChildren {
  ChatIdRoute: typeof ChatIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteRouteChildren: ChatRouteRouteChildren = {
  ChatIdRoute: ChatIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteRouteWithChildren = ChatRouteRoute._addFileChildren(
  ChatRouteRouteChildren,
)

interface SellerRouteRouteChildren {
  SellerProfileRouteRoute: typeof SellerProfileRouteRoute
  SellerProductsNewRouteRoute: typeof SellerProductsNewRouteRoute
  SellerFarmIndexRoute: typeof SellerFarmIndexRoute
  SellerProductsIndexRoute: typeof SellerProductsIndexRoute
  SellerProductsIdEditRouteRoute: typeof SellerProductsIdEditRouteRoute
}

const SellerRouteRouteChildren: SellerRouteRouteChildren = {
  SellerProfileRouteRoute: SellerProfileRouteRoute,
  SellerProductsNewRouteRoute: SellerProductsNewRouteRoute,
  SellerFarmIndexRoute: SellerFarmIndexRoute,
  SellerProductsIndexRoute: SellerProductsIndexRoute,
  SellerProductsIdEditRouteRoute: SellerProductsIdEditRouteRoute,
}

const SellerRouteRouteWithChildren = SellerRouteRoute._addFileChildren(
  SellerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CartRouteRoute: CartRouteRoute,
  CatalogRouteRoute: CatalogRouteRoute,
  ChatRouteRoute: ChatRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRoute,
  ProfileRouteRoute: ProfileRouteRoute,
  SellerRouteRoute: SellerRouteRouteWithChildren,
  SignupRouteRoute: SignupRouteRoute,
  FarmersIdRouteRoute: FarmersIdRouteRoute,
  FarmsIdRouteRoute: FarmsIdRouteRoute,
  ProductsIdRouteRoute: ProductsIdRouteRoute,
  FarmsIndexRoute: FarmsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
