import { BaseSeeder } from '@adonisjs/lucid/seeders'
import db from '@adonisjs/lucid/services/db'
import hash from '@adonisjs/core/services/hash'

export default class extends BaseSeeder {
  async run() {
    const password = await hash.make('password123')
    const now = new Date()

    const sellerRows = await db
      .table('users')
      .multiInsert([
        {
          email: 'maria@test.com',
          password,
          full_name: 'Марія Коваль',
          farm_name: 'Ферма Коваль',
          is_seller: true,
          phone: '+380671234567',
          created_at: now,
          updated_at: now,
        },
        {
          email: 'ivan@test.com',
          password,
          full_name: 'Іван Мельник',
          farm_name: 'Садиба Мельників',
          is_seller: true,
          phone: '+380507654321',
          telegram: '@ivan_melnyk',
          created_at: now,
          updated_at: now,
        },
        {
          email: 'oksana@test.com',
          password,
          full_name: 'Оксана Бондаренко',
          farm_name: 'Еко-ферма Бондаренків',
          is_seller: true,
          phone: '+380931112233',
          created_at: now,
          updated_at: now,
        },
        {
          email: 'petro@test.com',
          password,
          full_name: 'Петро Гриценко',
          farm_name: 'Пасіка Гриценка',
          is_seller: true,
          phone: '+380665559988',
          viber: '+380665559988',
          created_at: now,
          updated_at: now,
        },
        {
          email: 'halyna@test.com',
          password,
          full_name: 'Галина Шевченко',
          farm_name: 'Зелений хутір',
          is_seller: true,
          phone: '+380971234000',
          telegram: '@halyna_farm',
          created_at: now,
          updated_at: now,
        },
        {
          email: 'andriy@test.com',
          password,
          full_name: 'Андрій Савченко',
          farm_name: 'Рибне господарство Савченка',
          is_seller: true,
          phone: '+380631119977',
          created_at: now,
          updated_at: now,
        },
        {
          email: 'natalia@test.com',
          password,
          full_name: 'Наталія Лисенко',
          farm_name: 'Органік Поле',
          is_seller: true,
          phone: '+380503334455',
          created_at: now,
          updated_at: now,
        },
      ])
      .returning('id')

    const [maria, ivan, oksana, petro, halyna, andriy, natalia] = sellerRows.map(
      (r: any) => r.id as number
    )

    // buyer accounts
    await db.table('users').multiInsert([
      {
        email: 'buyer1@test.com',
        password,
        full_name: 'Олег Кравченко',
        is_seller: false,
        created_at: now,
        updated_at: now,
      },
      {
        email: 'buyer2@test.com',
        password,
        full_name: 'Тетяна Романюк',
        is_seller: false,
        created_at: now,
        updated_at: now,
      },
    ])

    const cats = await db.from('categories').select('id', 'slug')
    const cat = (slug: string) => cats.find((c: any) => c.slug === slug)!.id

    // Farms
    const farmRows = await db
      .table('farms')
      .multiInsert([
        {
          user_id: maria,
          name: 'Ферма Коваль',
          description:
            'Сімейна ферма у Київській області. Вирощуємо овочі та зелень без пестицидів вже 15 років. Власна корова дає молоко цілий рік.',
          location: 'Київська обл., Бориспільський р-н',
          activities: JSON.stringify(['vegetables', 'herbs', 'dairy']),
          created_at: now,
          updated_at: now,
        },
        {
          user_id: ivan,
          name: 'Садиба Мельників',
          description:
            'Великий сад з 200 деревами. Яблука, груші, сливи, вишні — все вирощено з любов’ю. Також тримаємо бджіл і виробляємо власне борошно.',
          location: 'Вінницька обл., Вінницький р-н',
          activities: JSON.stringify(['fruits', 'honey', 'grains']),
          instagram: 'sadyba_melnykiv',
          created_at: now,
          updated_at: now,
        },
        {
          user_id: oksana,
          name: 'Еко-ферма Бондаренків',
          description:
            'Сертифікована органічна ферма. Ніяких ГМО та хімікатів. М’ясо птиці та свинина від тварин на вільному вигулі.',
          location: 'Полтавська обл., Полтавський р-н',
          activities: JSON.stringify(['meat', 'dairy', 'vegetables']),
          created_at: now,
          updated_at: now,
        },
        {
          user_id: petro,
          name: 'Пасіка Гриценка',
          description:
            'Пасіка на 120 вуликів у Карпатах. Гірський мед, пилок, прополіс — все від власних бджіл. Доставляємо по всій Україні.',
          location: 'Івано-Франківська обл., Надвірнянський р-н',
          activities: JSON.stringify(['honey']),
          created_at: now,
          updated_at: now,
        },
        {
          user_id: halyna,
          name: 'Зелений хутір',
          description:
            'Спеціалізуємось на рідкісних сортах зелені, трав та екзотичних культурах. Вирощуємо базилік, руколу, шпинат та мікрозелень.',
          location: 'Харківська обл., Харківський р-н',
          activities: JSON.stringify(['herbs', 'vegetables', 'exotic']),
          created_at: now,
          updated_at: now,
        },
        {
          user_id: andriy,
          name: 'Рибне господарство Савченка',
          description:
            'Власні ставки площею 5 га. Короп, щука, карась, форель — все живе та свіже. Можна приїхати на рибалку або замовити доставку.',
          location: 'Черкаська обл., Уманський р-н',
          activities: JSON.stringify(['fish']),
          created_at: now,
          updated_at: now,
        },
        {
          user_id: natalia,
          name: 'Органік Поле',
          description:
            'Фермерське господарство з повним циклом: від зерна до борошна та крупів. Також вирощуємо бобові та олійні культури.',
          location: 'Дніпропетровська обл., Дніпровський р-н',
          activities: JSON.stringify(['grains', 'vegetables']),
          instagram: 'organik_pole_ua',
          created_at: now,
          updated_at: now,
        },
      ])
      .returning('id')

    const farmIds = farmRows.map((r: any) => r.id as number)
    const [mariaFarm, ivanFarm, oksanaFarm, petroFarm, , , natFarm] = farmIds

    // Farm reviews
    const buyerRows = await db.from('users').where('is_seller', false).select('id')
    const buyerId = buyerRows[0]?.id
    if (buyerId) {
      await db.table('farm_reviews').multiInsert([
        {
          farm_id: mariaFarm,
          user_id: buyerId,
          rating: 5,
          text: 'Чудова ферма! Овочі завжди свіжі та смачні. Рекомендую всім!',
          created_at: now,
        },
        {
          farm_id: mariaFarm,
          user_id: buyerId,
          rating: 4,
          text: 'Молоко дуже свіже, сметана смачна. Доставка трохи затрималась, але загалом задоволений.',
          created_at: now,
        },
        {
          farm_id: ivanFarm,
          user_id: buyerId,
          rating: 5,
          text: 'Мед неймовірний! Купую вже третій рік поспіль.',
          created_at: now,
        },
        {
          farm_id: oksanaFarm,
          user_id: buyerId,
          rating: 5,
          text: 'Справді органічне м’ясо, відчувається різниця зі звичайним магазинним.',
          created_at: now,
        },
        {
          farm_id: petroFarm,
          user_id: buyerId,
          rating: 5,
          text: 'Карпатський мед — це щось особливе. Замовляємо щороку.',
          created_at: now,
        },
        {
          farm_id: natFarm,
          user_id: buyerId,
          rating: 4,
          text: 'Борошно вищої якості, хліб виходить чудовий.',
          created_at: now,
        },
      ])
    }

    await db.table('products').multiInsert([
      // Марія — овочі, зелень, молочне
      {
        seller_id: maria,
        category_id: cat('vegetables'),
        name: 'Картопля молода',
        description: 'Свіжа молода картопля з власного городу, вирощена без хімії',
        price: 18,
        unit: 'кг',
        quantity: 200,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: maria,
        category_id: cat('vegetables'),
        name: 'Буряк столовий',
        description: 'Солодкий буряк, ідеальний для борщу та салатів',
        price: 12,
        unit: 'кг',
        quantity: 150,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: maria,
        category_id: cat('vegetables'),
        name: 'Морква',
        description: 'Соковита морква домашнього вирощування',
        price: 15,
        unit: 'кг',
        quantity: 100,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: maria,
        category_id: cat('vegetables'),
        name: 'Цибуля ріпчаста',
        description: 'Суха цибуля власного вирощування, лежкість до весни',
        price: 10,
        unit: 'кг',
        quantity: 300,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: maria,
        category_id: cat('vegetables'),
        name: 'Капуста білокачанна',
        description: 'Щільна капуста, ідеальна для квашення та борщу',
        price: 8,
        unit: 'кг',
        quantity: 400,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: maria,
        category_id: cat('vegetables'),
        name: 'Гарбуз Хокайдо',
        description: 'Солодкий гарбуз помаранчевого кольору, їдять разом зі шкіркою',
        price: 25,
        unit: 'кг',
        quantity: 60,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: maria,
        category_id: cat('vegetables'),
        name: 'Помідори Черрі',
        description: 'Дрібні солодкі помідорки, ідеальні для салатів',
        price: 55,
        unit: 'кг',
        quantity: 30,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: maria,
        category_id: cat('herbs'),
        name: 'Кріп свіжий',
        description: 'Пучок свіжого кропу, зібраного вранці',
        price: 8,
        unit: 'пучок',
        quantity: 50,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: maria,
        category_id: cat('herbs'),
        name: 'Петрушка',
        description: 'Ароматна петрушка з городу',
        price: 8,
        unit: 'пучок',
        quantity: 40,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: maria,
        category_id: cat('herbs'),
        name: 'Кінза',
        description: 'Свіжа кінза з характерним ароматом',
        price: 10,
        unit: 'пучок',
        quantity: 30,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: maria,
        category_id: cat('dairy'),
        name: 'Молоко домашнє',
        description: 'Свіже молоко від власної корови, жирність 3.8%',
        price: 35,
        unit: 'л',
        quantity: 20,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: maria,
        category_id: cat('dairy'),
        name: 'Сметана домашня',
        description: 'Густа натуральна сметана, жирність 25%',
        price: 80,
        unit: 'л',
        quantity: 10,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: maria,
        category_id: cat('dairy'),
        name: 'Масло вершкове',
        description: 'Домашнє масло з вершків без добавок, жирність 82%',
        price: 250,
        unit: 'кг',
        quantity: 5,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: maria,
        category_id: cat('dairy'),
        name: 'Сир кисломолочний',
        description: 'М’який домашній сир, зерниста текстура',
        price: 120,
        unit: 'кг',
        quantity: 8,
        status: 'active',
        created_at: now,
        updated_at: now,
      },

      // Іван — фрукти, мед, зернові
      {
        seller_id: ivan,
        category_id: cat('fruits'),
        name: 'Яблука Антонівка',
        description: 'Соковиті яблука сорту Антонівка з власного саду',
        price: 22,
        unit: 'кг',
        quantity: 300,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: ivan,
        category_id: cat('fruits'),
        name: 'Груші Вільямс',
        description: 'Стиглі солодкі груші, зібрані вручну',
        price: 35,
        unit: 'кг',
        quantity: 120,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: ivan,
        category_id: cat('fruits'),
        name: 'Сливи угорка',
        description: 'Темно-сині сливи, солодкі та соковиті',
        price: 28,
        unit: 'кг',
        quantity: 80,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: ivan,
        category_id: cat('fruits'),
        name: 'Вишні',
        description: 'Кисло-солодкі вишні, ідеальні для варення та компоту',
        price: 45,
        unit: 'кг',
        quantity: 60,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: ivan,
        category_id: cat('fruits'),
        name: 'Черешня Наполеон',
        description: 'Велика жовто-рожева черешня, дуже солодка',
        price: 65,
        unit: 'кг',
        quantity: 40,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: ivan,
        category_id: cat('fruits'),
        name: 'Аґрус',
        description: 'Зелений аґрус для варення та свіжого споживання',
        price: 38,
        unit: 'кг',
        quantity: 25,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: ivan,
        category_id: cat('fruits'),
        name: 'Смородина чорна',
        description: 'Велика соковита чорна смородина',
        price: 50,
        unit: 'кг',
        quantity: 20,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: ivan,
        category_id: cat('honey'),
        name: 'Мед акацієвий',
        description: 'Світлий рідкий мед з квітів акації, зібраний у травні',
        price: 180,
        unit: 'банка 0.5л',
        quantity: 30,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: ivan,
        category_id: cat('honey'),
        name: 'Мед гречаний',
        description: 'Темний ароматний мед з гречки, багатий на залізо',
        price: 200,
        unit: 'банка 0.5л',
        quantity: 25,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: ivan,
        category_id: cat('grains'),
        name: 'Борошно пшеничне',
        description: 'Борошно вищого ґатунку власного помелу',
        price: 45,
        unit: 'кг',
        quantity: 500,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: ivan,
        category_id: cat('grains'),
        name: 'Гречка зелена',
        description: 'Зелена гречка власного вирощування, без обробки',
        price: 55,
        unit: 'кг',
        quantity: 200,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: ivan,
        category_id: cat('grains'),
        name: 'Кукурудза сушена',
        description: 'Стиглі качани кукурудзи, висушені природнім способом',
        price: 30,
        unit: 'кг',
        quantity: 150,
        status: 'active',
        created_at: now,
        updated_at: now,
      },

      // Оксана — м’ясо, молочне, овочі
      {
        seller_id: oksana,
        category_id: cat('meat'),
        name: 'Свинина (лопатка)',
        description: 'Свіжа свинина від свиней на вільному вигулі, без антибіотиків',
        price: 185,
        unit: 'кг',
        quantity: 15,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: oksana,
        category_id: cat('meat'),
        name: 'Курятина ціла тушка',
        description: 'Домашня курка, вирощена на вільному вигулі, годована зерном',
        price: 160,
        unit: 'кг',
        quantity: 20,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: oksana,
        category_id: cat('meat'),
        name: 'Яловичина (вирізка)',
        description: 'Ніжна яловичина від молодих бичків, мармурове м’ясо',
        price: 280,
        unit: 'кг',
        quantity: 8,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: oksana,
        category_id: cat('meat'),
        name: 'Сало солоне',
        description: 'Домашнє сало з часником і перцем, посол 3 доби',
        price: 120,
        unit: 'кг',
        quantity: 12,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: oksana,
        category_id: cat('meat'),
        name: 'Ковбаса домашня',
        description: 'Домашня ковбаса зі свинини та яловичини зі спеціями',
        price: 220,
        unit: 'кг',
        quantity: 6,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: oksana,
        category_id: cat('dairy'),
        name: 'Яйця курячі',
        description: 'Яйця від курей вільного вигулу, жовток яскраво-помаранчевий',
        price: 6,
        unit: 'шт',
        quantity: 500,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: oksana,
        category_id: cat('dairy'),
        name: 'Яйця перепелині',
        description: 'Свіжі перепелині яйця, багаті на вітаміни',
        price: 4,
        unit: 'шт',
        quantity: 300,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: oksana,
        category_id: cat('vegetables'),
        name: 'Часник',
        description: 'Духмяний часник власного вирощування, сушений',
        price: 80,
        unit: 'кг',
        quantity: 25,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: oksana,
        category_id: cat('vegetables'),
        name: 'Картопля Бела Роса',
        description: 'Жовтоком’яна картопля, розсипчаста, ідеальна для пюре',
        price: 22,
        unit: 'кг',
        quantity: 180,
        status: 'active',
        created_at: now,
        updated_at: now,
      },

      // Петро — мед та продукти бджільництва
      {
        seller_id: petro,
        category_id: cat('honey'),
        name: 'Мед гірський',
        description: 'Унікальний карпатський мед з різнотрав’я, зібраний на висоті 800м',
        price: 350,
        unit: 'банка 0.5л',
        quantity: 40,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: petro,
        category_id: cat('honey'),
        name: 'Мед соняшниковий',
        description: 'Кристалізований мед з соняшника, солодкий та ароматний',
        price: 150,
        unit: 'банка 0.5л',
        quantity: 60,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: petro,
        category_id: cat('honey'),
        name: 'Мед липовий',
        description: 'Найкорисніший мед з лип, має протизапальні властивості',
        price: 320,
        unit: 'банка 0.5л',
        quantity: 20,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: petro,
        category_id: cat('honey'),
        name: 'Перга (бджолиний хліб)',
        description: 'Природній суперфуд, цвіткова пилок, ферментований бджолами',
        price: 600,
        unit: 'кг',
        quantity: 5,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: petro,
        category_id: cat('honey'),
        name: 'Прополіс настоянка',
        description: '30% настоянка прополісу на спирту, 50мл',
        price: 120,
        unit: 'пляшка',
        quantity: 15,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: petro,
        category_id: cat('honey'),
        name: 'Мед у стільниках',
        description: 'Незакритий мед просто у воску, 400г',
        price: 250,
        unit: 'шт',
        quantity: 10,
        status: 'active',
        created_at: now,
        updated_at: now,
      },

      // Галина — зелень, екзотика
      {
        seller_id: halyna,
        category_id: cat('herbs'),
        name: 'Базилік зелений',
        description: 'Свіжий зелений базилік з насиченим ароматом',
        price: 15,
        unit: 'пучок',
        quantity: 40,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: halyna,
        category_id: cat('herbs'),
        name: 'Базилік фіолетовий',
        description: 'Декоративний та ароматний фіолетовий базилік',
        price: 18,
        unit: 'пучок',
        quantity: 25,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: halyna,
        category_id: cat('herbs'),
        name: 'Рукола',
        description: 'Пряна рукола з горіховим смаком, ніжні молоді листки',
        price: 20,
        unit: 'пучок',
        quantity: 35,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: halyna,
        category_id: cat('herbs'),
        name: 'Шпинат',
        description: 'Молодий шпинат, багатий на залізо та вітаміни',
        price: 18,
        unit: 'пучок',
        quantity: 45,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: halyna,
        category_id: cat('herbs'),
        name: 'М’ята свіжа',
        description: 'Лимонна м’ята для чаю та десертів',
        price: 12,
        unit: 'пучок',
        quantity: 50,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: halyna,
        category_id: cat('herbs'),
        name: 'Мікрозелень (мікс)',
        description: 'Набір мікрозелені: редис, соняшник, горох. Суперфуд для салатів.',
        price: 60,
        unit: '100г',
        quantity: 20,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: halyna,
        category_id: cat('exotic'),
        name: 'Імбир свіжий',
        description: 'Свіжий корінь імбиру, вирощений у теплиці',
        price: 90,
        unit: 'кг',
        quantity: 10,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: halyna,
        category_id: cat('exotic'),
        name: 'Куркума свіжа',
        description: 'Свіжий корінь куркуми, яскраво-жовтий, ароматний',
        price: 120,
        unit: 'кг',
        quantity: 8,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: halyna,
        category_id: cat('exotic'),
        name: 'Лемонграс',
        description: 'Свіже стебло лемонграсу для азійських страв та чаю',
        price: 25,
        unit: 'пучок',
        quantity: 15,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: halyna,
        category_id: cat('vegetables'),
        name: 'Батат',
        description: 'Солодка картопля батат, фіолетовий та помаранчевий сорти',
        price: 75,
        unit: 'кг',
        quantity: 20,
        status: 'active',
        created_at: now,
        updated_at: now,
      },

      // Андрій — риба
      {
        seller_id: andriy,
        category_id: cat('fish'),
        name: 'Короп живий',
        description: 'Живий короп з власного ставка, від 1 кг',
        price: 95,
        unit: 'кг',
        quantity: 100,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: andriy,
        category_id: cat('fish'),
        name: 'Карась',
        description: 'Свіжий карась, ідеальний для смаження',
        price: 70,
        unit: 'кг',
        quantity: 50,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: andriy,
        category_id: cat('fish'),
        name: 'Форель радужна',
        description: 'Свіжа форель з чистої проточної води, ніжне рожеве м’ясо',
        price: 210,
        unit: 'кг',
        quantity: 30,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: andriy,
        category_id: cat('fish'),
        name: 'Щука',
        description: 'Свіжа щука, нежирне дієтичне м’ясо',
        price: 130,
        unit: 'кг',
        quantity: 20,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: andriy,
        category_id: cat('fish'),
        name: 'Товстолоб',
        description: 'Жирний товстолоб, ідеальний для запікання та юшки',
        price: 85,
        unit: 'кг',
        quantity: 60,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: andriy,
        category_id: cat('fish'),
        name: 'Рак річковий',
        description: 'Живі раки, розмір L та XL',
        price: 280,
        unit: 'кг',
        quantity: 15,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: andriy,
        category_id: cat('fish'),
        name: 'Короп копчений',
        description: 'Короп гарячого копчення, власне виробництво',
        price: 180,
        unit: 'кг',
        quantity: 10,
        status: 'active',
        created_at: now,
        updated_at: now,
      },

      // Наталія — зернові, бобові
      {
        seller_id: natalia,
        category_id: cat('grains'),
        name: 'Пшениця тверда (дурум)',
        description: 'Тверда пшениця для домашньої пасти та хліба',
        price: 28,
        unit: 'кг',
        quantity: 300,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: natalia,
        category_id: cat('grains'),
        name: 'Жито озиме',
        description: 'Органічне жито для цільнозернового борошна та квасу',
        price: 22,
        unit: 'кг',
        quantity: 200,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: natalia,
        category_id: cat('grains'),
        name: 'Ячмінь',
        description: 'Ячмінь для пивоваріння та перлової крупи',
        price: 18,
        unit: 'кг',
        quantity: 250,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: natalia,
        category_id: cat('grains'),
        name: 'Сочевиця зелена',
        description: 'Не варена сочевиця, джерело рослинного білку',
        price: 65,
        unit: 'кг',
        quantity: 100,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: natalia,
        category_id: cat('grains'),
        name: 'Нут',
        description: 'Великий нут, ідеальний для хумусу та плову',
        price: 70,
        unit: 'кг',
        quantity: 80,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: natalia,
        category_id: cat('grains'),
        name: 'Олія соняшникова нерафінована',
        description: 'Холодного пресування, з насіння власного вирощування',
        price: 120,
        unit: 'л',
        quantity: 50,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: natalia,
        category_id: cat('vegetables'),
        name: 'Гарбуз для насіння',
        description: 'Великий гарбуз з багатим насінням, можна їсти також м’якоть',
        price: 15,
        unit: 'кг',
        quantity: 70,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
      {
        seller_id: natalia,
        category_id: cat('vegetables'),
        name: 'Кукурудза цукрова',
        description: 'Молода цукрова кукурудза в качанах, дуже солодка',
        price: 20,
        unit: 'шт',
        quantity: 120,
        status: 'active',
        created_at: now,
        updated_at: now,
      },
    ])
  }
}
