/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CategorySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = CategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ConversationSchema extends BaseModel {
  static $columns = ['buyerId', 'createdAt', 'id', 'sellerId', 'updatedAt'] as const
  $columns = ConversationSchema.$columns
  @column()
  declare buyerId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare sellerId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class FarmPhotoSchema extends BaseModel {
  static $columns = ['createdAt', 'farmId', 'id', 'imagePath', 'position'] as const
  $columns = FarmPhotoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare farmId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imagePath: string
  @column()
  declare position: number
}

export class FarmReviewSchema extends BaseModel {
  static $columns = ['createdAt', 'farmId', 'id', 'rating', 'text', 'userId'] as const
  $columns = FarmReviewSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare farmId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare rating: number
  @column()
  declare text: string
  @column()
  declare userId: number
}

export class FarmSchema extends BaseModel {
  static $columns = ['activities', 'coverImagePath', 'createdAt', 'description', 'id', 'instagram', 'location', 'name', 'updatedAt', 'userId'] as const
  $columns = FarmSchema.$columns
  @column()
  declare activities: any
  @column()
  declare coverImagePath: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare instagram: string | null
  @column()
  declare location: string | null
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class MessageSchema extends BaseModel {
  static $columns = ['conversationId', 'createdAt', 'id', 'notificationSentAt', 'readAt', 'senderId', 'text', 'updatedAt'] as const
  $columns = MessageSchema.$columns
  @column()
  declare conversationId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare notificationSentAt: DateTime | null
  @column.dateTime()
  declare readAt: DateTime | null
  @column()
  declare senderId: number
  @column()
  declare text: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PasswordResetTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'token', 'userId'] as const
  $columns = PasswordResetTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare token: string
  @column()
  declare userId: number
}

export class ProductSchema extends BaseModel {
  static $columns = ['categoryId', 'createdAt', 'description', 'id', 'imagePath', 'name', 'price', 'quantity', 'sellerId', 'status', 'unit', 'updatedAt'] as const
  $columns = ProductSchema.$columns
  @column()
  declare categoryId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imagePath: string | null
  @column()
  declare name: string
  @column()
  declare price: string
  @column()
  declare quantity: string
  @column()
  declare sellerId: number
  @column()
  declare status: string
  @column()
  declare unit: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'farmName', 'fullName', 'id', 'isSeller', 'password', 'phone', 'telegram', 'updatedAt', 'viber'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare farmName: string | null
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isSeller: boolean
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare phone: string | null
  @column()
  declare telegram: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare viber: string | null
}
